dist: xenial
language: ruby
cache:
  - bundler
script:
  - ./scripts/test
notifications:
  email: false
  slack:
    rooms:
      secure: RG1/XJzg8GJZbdRiM8U75VD+UDPTQlyakSNvuJAA6P+RabcKQJC0EjKUldLuRYPPxRmzPp22E8YOMjjc7emArz7c7KoLS2NOEUqw1twt6VFZ39UbQ2Bckz8BeV8KxU17x0cEbdSvVc1OgK4CTvbeQUmGwQeXeuseBhqzJtQnej1LMFzRkmdkVl122ALH4PPlzK5AvbQTIhxC1iXLo75AIoktxmsP84T+SFG1iTmGFTjj+1Z/gp91+afF5RwbBACR1WBXyqA3l8nFql0T+ZWYxz6zC6H9HNHqhlXLBzl5oxN2i/MmDk20zVVYijga56q0HiFEfTYZx0JbCE3mWmoWpkTOPkTVfjyOCzV2nQXlv587xPzlHhvJBxeIU2jA0OWGynkmkm+dhyp/ja1L4pCmdJ5PBh5iIvGmRmT/J8CFJ6mhJfdLyZAggJjU9iz36cmgousDTq19RsEpQcQreVzRTouSoKVFBwEU44ADKQ5wGH8b8kO5w3b3nb3Z6MfTX7fhvvaeLT+3NuEwMZkpfYYJEQaVUWewEW9x0TXQ3yiBbtwJAL8HwYkCef9lJ//gIwu3iJqIBqC+Q6GN0KeIFcbjv/toMNTYA9DZ03MIKBUzSuiPADUg2LuQyY+j6IPfcsbL7qAKhRhzPTR40s8UwGkrYA0+qQqIP8Jlg26GlUpbI8Q=
