source: src
destination: ./public

include:
  - _headers
  - _redirects

host: 0.0.0.0

title: Defense Digital Service
description: An agency team of the United States Digital Service, using design and technology to improve the lives of American citizens.

domain: "https://dds.mil"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dds.mil"

# Social media
medium_url: https://medium.com/@DefenseDigitalService
twitter_url: https://twitter.com/DefenseDigital
linkedin_url: https://www.linkedin.com/company/defensedigitalservice
github_url: https://github.com/deptofdefense/

# Data settings
data_dir : _content

# Assets settings
sass:
  sass_dir: assets/stylesheets/
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclude from processing
exclude:
  - ".ruby-version"
  - ".sass-cache"
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - config
  - js
  - vendor
  - manifest.yml
  - node_modules
  - package.json
  - gulpfile.js
  - circle.yml
  - css
  - image-templates
  - CODE_OF_CONDUCT.md
  - package-lock.json
  - assets/uswds-theme
